### ISSUE TITLE
Batch Addition and Deletion of Policy rules.

### ISSUE THREAD

**Issue by divy9881** [node-casbin/mongoose-adapter#12]
The adapter should be extended to support features like Batch addition and deletion of policy rules.

**Comment by Sefriol** [comment]
Related https://github.com/node-casbin/mongoose-adapter/pull/8

**Comment by DivyPatel9881** [comment]
Is anyone working on this issue?

**Comment by hsluoyz** [comment]
@zhmushan @Sefriol can anyone work on this?

**Comment by Sefriol** [comment]
Kinda implemented in https://github.com/node-casbin/mongoose-adapter/pull/8/commits/fab5ec28854efdd5e874695622c833087c62ac49

**Comment by hsluoyz** [comment]
@Sefriol awesome! Closed.
