### ISSUE TITLE
addPolicy error

### ISSUE THREAD

**Issue by hehehai** [node-casbin/mongoose-adapter#14]
```js
async function setBasePolicy(e) {
  const rules = [
    ["root", "/*", "*"],
    ["read:authority", "/api/v1/authority", "GET"],
    ["read:authority", "/api/v1/authority/:id", "GET"],
    ["create:authority", "/api/v1/authority", "POST"],
    ["update:authority", "/api/v1/authority/:id", "PUT"],
    ["delete:authority", "/api/v1/authority/:id", "DELETE"],
    ["clear-cache", "/api/v1/admin", "DELETE"],
  ];
  rules.forEach(async (line) => {
    // console.log(line);
    await e.addPolicy("rules", "p", line);
  });
  const groups = [
    ["superuser", "root"],
    ["read", "read:authority"],
    ["create", "create:authority"],
    ["update", "update:authority"],
    ["delete", "delete:authority"],
    ["user", "read"],
    ["user", "create"],
    ["user", "update"],
    ["user", "delete"],
    ["fu", "user"],
  ];
  groups.forEach(async (line) => {
    await e.addPolicy("groups", "g", line);
  });
}
```
then run

![image](https://user-images.githubusercontent.com/12692552/85089072-3b2b3980-b214-11ea-9cc6-254ff265aade.png)

![image](https://user-images.githubusercontent.com/12692552/85089105-55fdae00-b214-11ea-9a22-91d17f5f5f49.png)

![image](https://user-images.githubusercontent.com/12692552/85089114-5b5af880-b214-11ea-90d6-c45238851dd5.png)

I don't understand why rules is not the parameter I pass, but arguments

**Comment by hsluoyz** [comment]
@nodece @zhmushan @Sefriol

**Comment by Sefriol** [comment]
I think you are mixing the idea between adapter and enforcer. Now you are trying to add policy straight to enforcer with adapter input.

For adapter (which you should not use directly):
`adapter.addPolicy('rules', 'p', ['root', '/*', '*'])`
where as for enforcer you use just:
`enforcer.addPolicy('root', '/*', '*')`

https://casbin.org/docs/en/management-api#addpolicy
And for groups:
https://casbin.org/docs/en/management-api#addgroupingpolicy

**Comment by hehehai** [comment]
@Sefriol 
 Sorry I confused adapter and enforcer.. I modified the code, now it can work properly! Thank you!
