### ISSUE TITLE
isFiltered incompatible with late node-casbin version

### ISSUE THREAD

**Issue by nmacherey** [node-casbin/mongoose-adapter#18]
Hi,

It seams now that isFiltered should be a function in the adapter and not only a property as last node casbin version >5.1. 
This causes errors when saving policies:

`TypeError: this.adapter.isFiltered is not a function`

Regards

**Comment by hsluoyz** [comment]
@nodece @zhmushan

**Comment by nodece** [comment]
@nmacherey Could you install latest `casbin-mongoose-adapter`? I fixed by #19 .

**Comment by hsluoyz** [comment]
v2.2.1: https://github.com/node-casbin/mongoose-adapter/releases/tag/v2.2.1

**Comment by nmacherey** [comment]
Perfect thanks 🙏 

Envoyé de mon iPhone
