### ISSUE TITLE
Performance improvement by using `lean`

### ISSUE THREAD

**Issue by murzatayev** [node-casbin/mongoose-adapter#20]
Hey guys,

We have noticed that this adapter has a very bad performance on large number of rules. The reason is that it is converting every received rule to mongoose doc. This operation is CPU intensive and blocks the thread. It really does not need to convert the rules to mongoose docs, because it does not seem to be using the provided features.

So adding `lean` on this line should make it a lot faster: https://github.com/node-casbin/mongoose-adapter/blob/master/src/adapter.js#L302

https://mongoosejs.com/docs/tutorials/lean.html

**Comment by hsluoyz** [comment]
@murzatayev very good finding! Can you make a PR to fix it?

/cc @nodece @zhmushan

**Comment by hsluoyz** [comment]
Merged: https://github.com/node-casbin/mongoose-adapter/pull/21

**Comment by murzatayev** [comment]
@hsluoyz thanks for approving the PR, can you please also publish a package version with this change?

**Comment by hsluoyz** [comment]
@nodece @zhmushan please make a new release.
