### ISSUE TITLE
Rewrite mongoose-adapter in Typescript?

### ISSUE THREAD

**Issue by rubek-joshi** [node-casbin/mongoose-adapter#24]
I think this project should be rewritten in typescript and it would be helpful if there was a `@types/casbin-mongoose-adapter` package to handle the types. The `node-casbin` has been written in typescript so I am a bit surprised to find that this package was not written in typescript.

**Comment by hsluoyz** [comment]
@rubek-joshi this is because this is originally a fork project from a 3rd-party and recently moved here :) I think it's a good idea to rewrite it in TS. But we need to first find someone to work on it. Are you willing to contribute to this ?

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@rubek-joshi If you need, I will publish a `@types/casbin-mongoose-adapter` package later.

**Comment by Zxilly** [comment]
@hsluoyz Maybe there is no need to totally refactor the package. I will make a type definition package.

**Comment by hsluoyz** [comment]
@Zxilly OK, type definition also sounds good!

**Comment by hsluoyz** [comment]
@Yash-g17

**Comment by Yash-g17** [comment]
@Zxilly , should I start working on this ?

**Comment by Zxilly** [comment]
@Zxilly my work is nearly completed. You can find another issue
