### ISSUE TITLE
Add more complete tests and add GitHub Actions CI

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/mongoose-adapter#27]
See: https://github.com/node-casbin/mongoose-adapter/pull/26#issuecomment-813062969

**Comment by Sefriol** [comment]
I have not looked into Github Actions this much, but Transactions do need a MongoDB cluster to work. I am not sure how much work it requires to implement in Github CI.

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
@Sefriol I'm working on a solution. Maybe I will publish it as a GitHub Action template later.
And I will also add unnitest for one instance user.
