### ISSUE TITLE
Release new TypeScript bundle to `npm`

### ISSUE THREAD

**Issue by fdionisi** [node-casbin/mongoose-adapter#32]
Hi there, I was playing around with casbin and this mongoose adapter when I noticed the one published on `npm` is an _older_ version.

The latest version on `npm` seems to be `v2.2.3`; I'd love to take advantage of the newly added typings (kudos for the transition to TypeScript).
Is there any timeline for a new release? Can I help to get this going?

Thank you very much for reviving this adapter.

**Comment by hsluoyz** [comment]
@Zxilly plz make a new release on both GitHub Releases and NPMJS. Better setup semantic-release

**Comment by Zxilly** [comment]
working on this

**Comment by Zxilly** [comment]
The release is available on:
- [npm package](https://www.npmjs.com/package/casbin-mongoose-adapter/v/3.0.0)
- [GitHub release](https://github.com/node-casbin/mongoose-adapter/releases/tag/v3.0.0)

**Comment by hsluoyz** [comment]
@Zxilly plz use GitHub-Actions-bot account to publish the new release message instead:

![image](https://user-images.githubusercontent.com/3787410/115854224-9c3b2380-a45c-11eb-9133-e967532001ec.png)

**Comment by Zxilly** [comment]
@hsluoyz Have setup it. Since this issue not linked to the PR, so I manully sent it.
