### ISSUE TITLE
Add semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [node-casbin/mongoose-adapter#35]
See: https://github.com/node-casbin/mongoose-adapter/issues/32#issuecomment-824924805

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
working on this

**Comment by hsluoyz** [comment]
@Zxilly see error: https://github.com/node-casbin/mongoose-adapter/actions/runs/776240435
