### ISSUE TITLE
Install TypeScript as part of `devDependencies`

### ISSUE THREAD

**Issue by fdionisi** [node-casbin/mongoose-adapter#39]
Looking at the [`package.json`](https://github.com/node-casbin/mongoose-adapter/blob/master/package.json#L85), I noticed that the TypeScript npm package is installed as a direct dependency.

https://github.com/node-casbin/mongoose-adapter/blob/dca7419d192045467a7d7b37806afecfb89d6b77/package.json#L81-L86

This means that every production installations of software depending on `casbin-mongoose-adapter` will have an often superfluous module, making `node_modules/` a little bit bigger.

I suggest moving TypeScript dependency to `devDependencies` instead.

Before opening a PR, I wanted to ensure there is no hidden reason behind your initial decision.

**Comment by hsluoyz** [comment]
@Zxilly @Sefriol

**Comment by Zxilly** [comment]
@fdionisi Yes, you are right. PR is welcomed.
