### ISSUE TITLE
What to do with taken name on npm

### ISSUE THREAD

**Issue by ghaiklor** [node-casbin/mongoose-adapter#4]
@hsluoyz I'd like to bring the question regard taken name on npm.

AFAIR, @szy0syz had only stubs and no actual implementation for the adapter, while I was developing our own for elastic.io. Therefore, at this moment (almost a year later), we have two adapters that are doing the same.

My proposal is to merge these two codebases (in case it makes sense) and publish them under the proper name. Though, I went through the code and seems like @szy0syz just ported the Go implementation, so it is the same as ours + we already covered few edge-cases and have tests.

Here is my plan:

- @szy0syz transfers npm name ownership to our organization
- We are looking into both mine and his implementation in case there is something interesting to merge back into our official implementation
- Publish the major update (in case, someone already using @szy0syz implementation and just in case to prevent any outage)

Thoughts?

**Comment by hsluoyz** [comment]
@ghaiklor Good idea. I already sent a mail to @szy0syz, waiting for reply.

**Comment by szy0syz** [comment]
Sorry, I didn't do it well.
Then I am going to rename my package?

**Comment by hsluoyz** [comment]
@szy0syz No. We just want to merge the contributions into one for a specific adapter, to avoid duplicated efforts. I have invited you as a member to better maintain the new adapter code.

> Then I am going to rename my package?

You can transfer that package to our org: https://www.npmjs.com/org/casbin based on: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account

Renaming your package to another name is also OK.

**Comment by szy0syz** [comment]
I have completed the steps according to 
“Transferring a package from a user account to an Org on the website.”

<img width="798" alt="2019-10-31 下午10 08 55" src="https://user-images.githubusercontent.com/10555820/67953968-15bcd180-fc2b-11e9-9724-ff599ada98eb.png">

Is it right?

**Comment by hsluoyz** [comment]
Why does it show nodece instead of Casbin?

**Comment by hsluoyz** [comment]
@nodece are you owner now? Can you re-transfer it to Casbin?

**Comment by nodece** [comment]
@hsluoyz `node-casbin/casbin-mongoose-adapter` has been transfer to Casbin.

**Comment by nodece** [comment]
Casbin owner : @hsluoyz , @nodece

**Comment by nodece** [comment]
Hi @ghaiklor , I've invited you to join Casbin in npm.

**Comment by hsluoyz** [comment]
@ghaiklor @szy0syz @nodece thanks you all !

v2.0.0 is published: https://www.npmjs.com/package/casbin-mongoose-adapter

Feel free to improve the code and we can release new versions :)
