### ISSUE TITLE
Issues working with TypeScript

### ISSUE THREAD

**Issue by fdionisi** [node-casbin/mongoose-adapter#42]
First of all, thank you very much @Zxilly to take ownership of #41 and bringing it to a merge. Much appreciated 🙇‍♂️.

With this ticket, I want tightly two issues caused by the same code.

The root problem is the [`export = MongooseAdapter`](https://github.com/node-casbin/mongoose-adapter/blob/ddf23a7a6fc1720b693285005da12e52fe5ab13c/src/index.ts#L7) line.

It was added to maintain backwards compatibility, but it causes problems both, with TypeScript and with named exports.

### TS2309: An export assignment cannot be used in a module with other exported elements.
Under certain configurations, upon transpile time, third party libraries will be checked. In these cases, TypeScript compiler will throw the title's error:
```
$ tsc
node_modules/casbin-mongoose-adapter/lib/cjs/index.d.ts:5:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

5 export = MongooseAdapter;
  ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

### TypeError: Cannot read property 'newAdapter' of undefined

In the same [`index.ts`](https://github.com/node-casbin/mongoose-adapter/blob/ddf23a7a6fc1720b693285005da12e52fe5ab13c/src/index.ts), we are exporting _everything_ from internal files through `export *`. Therefore, I'd expect the following to work:
```ts
import { MongooseAdapter } from "casbin-mongoose-adapter"
```

While type-checking will not throw any error, this action will break in real-world usage.

This happen, because the same statement above (i.e. [`export = MongooseAdapter`](https://github.com/node-casbin/mongoose-adapter/blob/ddf23a7a6fc1720b693285005da12e52fe5ab13c/src/index.ts#L7)) actually overrides the `export *` statements (visible in the transpiled JavaScript).

---

For clarity and reproducibility, I create a repository where you can try yourself these issues"
https://github.com/fdionisi/casbin-mongoose-adapter-issues

---

The first issue could be fixed simply by forcing the `ts-ignore` comment to stay after transpilation to JavaScript. 

Instad of `// @ts-ignore` we can simply write `/** @ts-ignore */`. 

For the second issue, I don't know how it could be achievable. I tried with simply `export default` but that doesn't work well with CommonJS.

---

Sorry for the long report. I tried to add as much information as possible.
I'd be happy to open a PR to fix these issues once we agree on the direction to take.

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
> For the second issue, I don't know how it could be achievable. I tried with simply export default but that doesn't work well with CommonJS.

Yes, it should be used like `require(xxx).default`.

I will abandon legacy require import in TypeScript.

**Comment by hsluoyz** [comment]
@Zxilly plz fix it.
