### ISSUE TITLE
If any policy parameter value is empty or "" ,loadPolicyLine method is not handling in right way

### ISSUE THREAD

**Issue by Pyav123** [node-casbin/mongoose-adapter#46]
If we don't pass some parameter while defining policy and  by default we try to assign blank or "", then when the loadPolicyLine method triggers it overwrites the value by next subsequent value

e.g. configuration file looks like below

```ini
[request_definition]
r = subject,object,action,org

[policy_definition]
p = rule,subject,object,action,org
 
[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = eval(p.rule)
```

And below is the example for policy  where v2/object is blank

```json
{
  _id:ObjectId(id),
    p_type:"p",
    v0:"(r.subject == p.subject && r.object == p.object  && r.action == p.action  &&  r.org == p.org)",
    v1:"alice",
    v2:"",
    v3:"create",
    v4:"sampleOrg"
}
```

While loading this policy loadPolicyLine method reads as below

```ini
p,(r.subject == p.subject && r.object == p.object  && r.action == p.action  &&  r.org == p.org),alice,create,sampleOrg
```

as blanks are omitted n that method and considers "create" as subject and ""sampleOrg" as action.
Ideally it should read as 

```ini
p,(r.subject == p.subject && r.object == p.object  && r.action == p.action  &&  r.org == p.org),alice,,create,sampleOrg
```

leaving subject as blank

This affects the enforce decision as the whole sequence gets shuffled

**Comment by hsluoyz** [comment]
@ghaiklor @Zxilly @Gabriel-403 

/cc @nodece

**Comment by ghaiklor** [comment]
@hsluoyz I no longer work with Node.js and Casbin, so I have no input on those PRs 🙂
