### ISSUE TITLE
Update policy: implement the UpdatableAdapter interface in this adapter

### ISSUE THREAD

**Issue by Pyav123** [node-casbin/mongoose-adapter#48]
Which method I can use from adapter if I want to update policy ?

**Comment by hsluoyz** [comment]
We need to implement the UpdatableAdapter interface in this adapter, see: https://github.com/casbin/node-casbin/issues/229

**Comment by hsluoyz** [comment]
@Zxilly @Gabriel-403

**Comment by Pyav123** [comment]
@hsluoyz , I didn't mention clearly , but I am looking for update policy using mongoose adapter , I could see add and remove ,but don't see any method for update in adapter code , correct me if I am wrong.

**Comment by Zxilly** [comment]
@Pyav123  Hello, I'm the maintainer of this library. You do not need to do anything for this purpose. As for now, this function didn't exist in this adapter, and we will later add it.
