### ISSUE TITLE
Property 'mongooseInstance' is private and only accessible within class 'MongooseAdapter'.

### ISSUE THREAD

**Issue by StefanoPastore** [node-casbin/mongoose-adapter#53]
Hi,

I have to use the mongoose instance from adapter in order to make multiple mongoose connections one for casbin and one for the app.
Can you expose the mongoose instance as public property?

Thanks.

**Comment by hsluoyz** [comment]
@StefanoPastore hi, can you make a PR to support it?

**Comment by StefanoPastore** [comment]
@hsluoyz Hi, sure! I've made it #54 . 
Thanks.
