### ISSUE TITLE
Mongoose adapter not working properly help needed

### ISSUE THREAD

**Issue by RunnSC** [node-casbin/mongoose-adapter#55]
I think it is not connecting to my database im doing something wrong please fix me

```js
const path = require('path');
const { newEnforcer } = require('casbin');
const { MongooseAdapter } = require('casbin-mongoose-adapter');

async function main() {
  const model = path.resolve(__dirname, './model.conf');
  const adapter = await MongooseAdapter.newAdapter('mongodb://127.0.0.1:27017');
  const enforcer = await newEnforcer(model, adapter);

  console.log(await enforcer.getPermissionsForUser('alice'));
}

main();
```
the output is empty list

model

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act
```

policy
![asdasd](https://user-images.githubusercontent.com/59172531/154432893-56867d43-81eb-48e4-bab2-d332a604e5db.PNG)

When I add policy after that then it shows [ [ 'alice', 'data1', 'read' ] ]. It is not picking the policy from the db
```js
  const model = path.resolve(__dirname, './model.conf');
  const adapter = await MongooseAdapter.newAdapter('mongodb://localhost:27017');
  const enforcer = await newEnforcer(model, adapter);

  console.log(await enforcer.getPermissionsForUser('alice'));
  await enforcer.addPolicy('alice', 'data1', 'read');
```
output -> [ [ 'alice', 'data1', 'read' ] ]

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 @fabian4 

/cc @nodece

**Comment by RunnSC** [comment]
And btw where do we set the database name and collection name

**Comment by Shivansh-yadav13** [comment]
@RunnSC, I think when you init the adapter it does not get the policies from the db but when you add a policy using the `addPolicy()` it adds it in the db.

Not sure but can be a bug Ig.

**Comment by Shivansh-yadav13** [comment]
can you show how your policies are stored in the db.

**Comment by Shivansh-yadav13** [comment]
Ok, so I think it is happening because of the empty fields you have `v3 v4 v5`.
when we `addPolicy` let's say `p, alice, data1, read` it adds it with no empty fields and counts only that one.

**Comment by hsluoyz** [comment]
@Shivansh-yadav13 is this a breaking change? If yes, plz recall the previous version and make PR to send major release

**Comment by nodece** [comment]
#56 has a breaking change, which needs to release a major version, not a minor version.  Right now we need to revert #56, and publish a minor version to avoid breaking the user data.

But the way we also need to deprecate the v4.0.2 on npm.

**Comment by Shivansh-yadav13** [comment]
sorry for breaking change making a PR.

**Comment by nodece** [comment]
I submitted https://github.com/node-casbin/mongoose-adapter/pull/58 to revert the #56. Could you take a look?

**Comment by Sefriol** [comment]
Why is this change required at all? `p_type` has been used for 3 years and changing that would require all existing policies to be modified. Adapter should never had saved the policy in `ptype` format and  I don't see that even possible.

@RunnSC How did you add the original permission? Using `enforcer.addPermissionForUser('alice', 'data1', 'read')`, `enforcer.addPolicy('alice', 'data1', 'read')` or did you write it manually to the database?

**Comment by Shivansh-yadav13** [comment]
most probably the reason could be because in other in other go mongodb adapter the field is `ptype` so he might be trying to use the same database here

**Comment by RunnSC** [comment]
I had used the Golang MongoDB adapter before

**Comment by RunnSC** [comment]
that is my mistake sorry

**Comment by RunnSC** [comment]
Let's not change it to ptype then it is a breaking change for people who using it for their work

**Comment by Zxilly** [comment]
@Shivansh-yadav13 We do have a uniform code, this is a historical legacy

**Comment by Sefriol** [comment]
Unifying is a great idea especially if you have multiple clients accessing the same database from different code sources. However, I think previous versions should have an easy and reliable upgrade path to new version. Currently both mongoose adapters featured at casbin site use this naming convention.

**Comment by hsluoyz** [comment]
> Currently both mongoose adapters featured at casbin site use this naming convention.

Where?

**Comment by Sefriol** [comment]
https://casbin.org/docs/en/adapters
https://github.com/minhducck/casbin-mongoose-adapter

**Comment by hsluoyz** [comment]
OK. If anyone wants to take this task, it would be great. Any suggestion and plan is welcome. Does Mongoose have a migration facility?

**Comment by RunnSC** [comment]
what do you mean migration

**Comment by hsluoyz** [comment]
Auto-migration, like python's https://github.com/sqlalchemy/alembic . Does Node.js have such similar toolset?

**Comment by Sefriol** [comment]
Probably most preferable way is to use something like:
https://github.com/balmasi/migrate-mongoose
https://github.com/seppevs/migrate-mongo

Migrations should also use transactions (if available) and tests should be added for both up and down operations.

**Comment by hsluoyz** [comment]
@Sefriol can you create an issue for it?
