### ISSUE TITLE
不应该强制开启Mongo事务

### ISSUE THREAD

**Issue by Hareis** [node-casbin/mongoose-adapter#65]
mongoose 中已经存在了批量操作的方法

当我使用addPolicies时候 发现要打开同步开关，而同步开关则会开启数据库事务，请问有什么办法能解决这个问题吗？

提示：Transaction numbers are only allowed on a replica set member or mongos

**Comment by hsluoyz** [comment]
@Hareis hi, this community uses English to communicate. Please create a new issue which uses English only. This issue soon will be closed.
