### ISSUE TITLE
Need help in creating multiple adapter

### ISSUE THREAD

**Issue by shubhanshusingh** [node-casbin/mongoose-adapter#67]
I have multiple databases in single mongo instance.
I wish to create  multiple adapter and enforcer for each database in order to direct Casbin rules CRUD operations to databases.
How can I do it?

```node
   let config = Object.assign({}, vaultConfig.mongo);
  let host = "mongodb://" + config.host;
  delete config.host;
  config.dbName = "baymax-prod";
  const adapter = await MongooseAdapter.newAdapter(host, {
    ...config
  });
  const enforcer = await casbin.newEnforcer(
    "src/domain_role_model.conf",
    adapter
  );
  let config1 = Object.assign({}, config);
  config1.dbName = "baymax-stage";
  const adapter1 = await MongooseAdapter.newAdapter(host, {
    ...config1
  });
  const enforcer1 = await casbin.newEnforcer(
    "src/domain_role_model.conf",
    adapter1
  );
  
  let b2 = await enforcer.addPolicy("admin", "tenant1", "experiment", "W");

 
  let b22 = await enforcer1.addPolicy("admin", "tenant1", "experiment", "W");
  ```
  
  Above code is updating policies to same database which is initialised first i.e. baymax-prod.
  Adapter1 and Enforcer1 are saving policies to baymax-prod database instead of baymax-stage database.
  
  can someone help?

**Comment by shubhanshusingh** [comment]
I have one mongo db instance where I multiple databases.[]
<img width="245" alt="Screenshot 2023-04-18 at 9 12 03 PM" src="https://user-images.githubusercontent.com/8102163/232830334-df3895e7-e31a-4b42-a0a5-383a9f7d8d75.png">
(url)

Now I wish to connect to each db via mongoose casbin adapter? how can I do it?

**Comment by nodece** [comment]
Let me fix this issue.

**Comment by shubhanshusingh** [comment]
@nodece  appreciate it! it's much need requirement for my application.

**Comment by shubhanshusingh** [comment]
I tested that build @nodece  working perfectly, waiting for PR to be merged. Life saver!
